//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Photographs')
export class PhotographsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  imageUrl: string;

  @Column('text', { nullable: true })
  caption: string;

  @Column('text', { nullable: true })
  photographerName: string;

  @Column('date', { nullable: true })
  dateTaken: Date;
}
