//Source code generated by AppGPT (www.appgpt.tech)
import { Admin, Resource, CustomRoutes } from 'react-admin';
import { customDataProvider } from './dataProvider';
import fakeDataProvider from 'ra-data-fakerest';
import { Dashboard } from './dashboard';
import { authProvider, apInitialize } from './authProvider';
import { i18nProvider } from './i18nProvider';
import LoginPage, { Login } from './Login';
import data from './data';
import {
  NewsUpdatesList,
  NewsUpdatesCreate,
  NewsUpdatesEdit,
} from './resources/NewsUpdates';
import {
  EntertainmentList,
  EntertainmentCreate,
  EntertainmentEdit,
} from './resources/Entertainment';
import {
  PhotographsList,
  PhotographsCreate,
  PhotographsEdit,
} from './resources/Photographs';
import NewsUpdatesIcon from '@mui/icons-material/Article';
import EntertainmentIcon from '@mui/icons-material/Movie';
import PhotographsIcon from '@mui/icons-material/Photo';
// SUPERTOKENS
import React from 'react';
import SuperTokens, {
  SuperTokensWrapper,
  getSuperTokensRoutesForReactRouterDom,
} from 'supertokens-auth-react';
import ThirdPartyPasswordless from 'supertokens-auth-react/recipe/thirdpartypasswordless';
import Session from 'supertokens-auth-react/recipe/session';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import * as reactRouterDom from 'react-router-dom';
let sessionFn = Session.init();
SuperTokens.init({
  appInfo: {
    appName: import.meta.env.VITE_SUPERTOKENS_APPNAME,
    apiDomain: import.meta.env.VITE_BACKEND_DOMAIN,
    websiteDomain: import.meta.env.VITE_SUPERTOKENS_WEBSITEDOMAIN,
    apiBasePath: import.meta.env.VITE_BACKEND_APIPATH + '/auth',
    websiteBasePath: import.meta.env.VITE_SUPERTOKENS_WEBSITEBASEPATH,
  },
  recipeList: [
    ThirdPartyPasswordless.init({
      contactMethod: 'EMAIL',
      signInUpFeature: {
        providers: [
          ThirdPartyPasswordless.Github.init(),
          //ThirdPartyPasswordless.Google.init(),
          //ThirdPartyPasswordless.Facebook.init(),
          //ThirdPartyPasswordless.Apple.init(),
        ],
      },
    }),
    sessionFn,
  ],
});
apInitialize(Session);
// END SUPERTOKENS
let dataProvider: any;
if (import.meta.env.VITE_USE_BACKEND_DATA === 'true') {
  dataProvider = customDataProvider(
    import.meta.env.VITE_BACKEND_DOMAIN +
      import.meta.env.VITE_BACKEND_APIPATH +
      '/proxy',
  );
} else {
  dataProvider = fakeDataProvider(data.defaultData);
}

const App = () => (
  <SuperTokensWrapper>
    <BrowserRouter basename="/a2927bcb2">
      <Admin
        authProvider={
          import.meta.env.VITE_ENVIRONMENT != 'DEV' ? authProvider : undefined
        }
        requireAuth
        loginPage={LoginPage}
        dataProvider={dataProvider}
        i18nProvider={i18nProvider}
        dashboard={Dashboard}
      >
        <Resource
          name="NewsUpdates"
          options={{ label: 'News Updates' }}
          list={NewsUpdatesList}
          create={NewsUpdatesCreate}
          edit={NewsUpdatesEdit}
          recordRepresentation="title"
          icon={NewsUpdatesIcon}
        />
        <Resource
          name="Entertainment"
          options={{ label: 'Entertainment' }}
          list={EntertainmentList}
          create={EntertainmentCreate}
          edit={EntertainmentEdit}
          recordRepresentation="title"
          icon={EntertainmentIcon}
        />
        <Resource
          name="Photographs"
          options={{ label: 'Photographs' }}
          list={PhotographsList}
          create={PhotographsCreate}
          edit={PhotographsEdit}
          recordRepresentation="imageUrl"
          icon={PhotographsIcon}
        />
        <CustomRoutes noLayout>
          {/*This renders the login UI on the /auth route*/}
          {getSuperTokensRoutesForReactRouterDom(reactRouterDom)}
          {/*Your app routes*/}
        </CustomRoutes>
      </Admin>
    </BrowserRouter>
  </SuperTokensWrapper>
);

export default App;
