//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    NewsUpdates: {
      name: 'News Updates',
      fields: {
        title: 'Title',
        content: 'Content',
        publicationDate: 'Publication Date',
        author: 'Author',
        id: 'id',
      },
    },
    Entertainment: {
      name: 'Entertainment',
      fields: {
        title: 'Title',
        description: 'Description',
        category: 'Category',
        publicationDate: 'Publication Date',
        id: 'id',
      },
    },
    Photographs: {
      name: 'Photographs',
      fields: {
        imageUrl: 'Image Url',
        caption: 'Caption',
        photographerName: 'Photographer Name',
        dateTaken: 'Date Taken',
        id: 'id',
      },
    },
  },
};
const frResources = {
  resources: {
    NewsUpdates: {
      name: 'News Updates (fr)',
      fields: {
        title: 'Title (fr)',
        content: 'Content (fr)',
        publicationDate: 'Publication Date (fr)',
        author: 'Author (fr)',
        id: 'id',
      },
    },
    Entertainment: {
      name: 'Entertainment (fr)',
      fields: {
        title: 'Title (fr)',
        description: 'Description (fr)',
        category: 'Category (fr)',
        publicationDate: 'Publication Date (fr)',
        id: 'id',
      },
    },
    Photographs: {
      name: 'Photographs (fr)',
      fields: {
        imageUrl: 'Image Url (fr)',
        caption: 'Caption (fr)',
        photographerName: 'Photographer Name (fr)',
        dateTaken: 'Date Taken (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
